### PR TITLE
Enable to support windows system for reading some tpr files.

### PR DESCRIPTION
**Pull request by liuyujie714**
Add gromacs internal xdr library used on windows, and enable to support read tpr file on windows.
Add read atoms velocities
However, some version tpr still can not read successfully, I think this code needs to be improved

### CODE REVIEW

**Comment by jvermaas** [comment]
Cool! Which tprs fail? Can you attach them here so I can see what features we are missing? I recall restraints being a bit of a bear to read, and since I never use them, I skipped that part. I'm also a bit leery of using the giant GROMACS codeblocks, mostly since I don't understand what they are doing.

**Comment by liuyujie714** [comment]
> Cool! Which tprs fail? Can you attach them here so I can see what features we are missing? I recall restraints being a bit of a bear to read, and since I never use them, I skipped that part. I'm also a bit leery of using the giant GROMACS codeblocks, mostly since I don't understand what they are doing.

[error.tar.gz](https://github.com/jvermaas/vmd-tprreader/files/5746487/error.tar.gz)
Append a few tpr files that vmd-tpr can not read,

**Comment by jvermaas** [comment]
Ok, I played around with this a bit more over the past few days. I can get these all to read now with what is in master. I'll need to see what the conflicts are that I introduced, and see if there is a cleverer way around adding all the GROMACS dependencies.

**Comment by jvermaas** [comment]
Thanks @liuyujie714 , I think I've gotten everything sorted out now. On my testing platforms (all Linux unfortunately), your additions work, although I had to change back some of the uchar reading behavior. The next step would be to figure out what to do about the GROMACS code dependencies.

**Comment by liuyujie714** [comment]
> Thanks @liuyujie714 , I think I've gotten everything sorted out now. On my testing platforms (all Linux unfortunately), your additions work, although I had to change back some of the uchar reading behavior. The next step would be to figure out what to do about the GROMACS code dependencies.

Good Job! It works fine in vmd1.9.4 on windows, although some bonds of molecule looks maybe wrong.
For example, for my graphene+C60 system[2020.4_gra.tpr], it has too many wrong bonds between atoms [see picture]. Other system is ok.
Maybe Periodic boundary condition (pbc) leads this wrong show? My graphene is infinite along x and y axis
error_bonds

**Comment by jvermaas** [comment]
@liuyujie714 , yes, its a PBC issue. In the tpr, the respective atoms are bonded, and so VMD dutifully draws them. Since the atoms are far apart, you get super long bonds, and unfortunately that is just one of VMD's limitations. I often use a representation that doesn't show bonds (like VDW) for systems like this.

**Pull request merged**
